### ISSUE TITLE
Configure NavX to use SPI instead of I2C

### ISSUE THREAD

**Issue by HarrisHamid** [Team293/ProtoBot#2]
https://github.com/Team293/RapidReact/blob/bd21a244cbfac7523d0bbfe4bd445303996d4461/src/main/java/frc/robot/subsystems/Drivetrain.java#L107

https://docs.wpilib.org/en/stable/docs/yearly-overview/known-issues.html#onboard-i2c-causing-system-lockups

According to the article, there may be lockups using I2C therefore the NavX should be configured to use SPI instead of I2C.
Should look similar to "ahrs = new AHRS(SPI.Port.kMXP);"

**Comment by karthikappana35** [comment]
We use the I2C port that doesn't have this issue(MXP)
